### ISSUE TITLE
No indication of failure when a fit is imported from clipboard

### ISSUE THREAD

**Issue by Grimnir09** [EVEShipFit/roadmap#52]
### Expected result

A Popup, or Alert should should be visible to the user showing what modules are invalid in the clipboard import.

### Actual result

Visually, nothing happens, and a uncaught error is logged into the web console. 
Uncaught Error: Unknown item 'Federation Navy 100MN Afterburner [1]'.

### Steps to reproduce

1. Use the following fit which includes a  abyssal 100nm ( this is just an example copied from pyfa )
```
[Legion, pewpew]

Reactive Armor Hardener
Damage Control II
Ballistic Control System II
Corelum C-Type Multispectrum Energized Membrane
Corelum C-Type Multispectrum Energized Membrane
Corpum A-Type Medium Armor Repairer

Federation Navy 100MN Afterburner [1]
Medium F-RX Compact Capacitor Booster
Caldari Navy Stasis Webifier
Caldari Navy Warp Disruptor

Heavy Assault Missile Launcher II, Mjolnir Rage Heavy Assault Missile
True Sansha Medium Energy Neutralizer
Heavy Assault Missile Launcher II, Mjolnir Rage Heavy Assault Missile
Heavy Assault Missile Launcher II, Mjolnir Rage Heavy Assault Missile
Expanded Probe Launcher II
Heavy Assault Missile Launcher II, Mjolnir Rage Heavy Assault Missile
True Sansha Medium Energy Neutralizer

Medium Ancillary Current Router II
Medium Ancillary Current Router II
Medium Auxiliary Nano Pump I

Legion Core - Energy Parasitic Complex
Legion Defensive - Nanobot Injector
Legion Offensive - Assault Optimization
Legion Propulsion - Intercalated Nanofibers


Caldari Navy Hornet x5
Caldari Navy Vespa x7
Imperial Navy Infiltrator x8
Hornet EC-300 x5


Mid-grade Asklepian Alpha
Mid-grade Asklepian Beta
Mid-grade Asklepian Gamma
Mid-grade Asklepian Delta
Mid-grade Asklepian Epsilon
Mid-grade Asklepian Omega
Inherent Implants 'Noble' Remote Armor Repair Systems RA-703
Inherent Implants 'Squire' Capacitor Management EM-803
Inherent Implants 'Noble' Repair Proficiency RP-903

Strong Exile Booster
Agency 'Hardshell' TB9 Dose IV


Inferno Javelin Heavy Assault Missile x600
Inferno Rage Heavy Assault Missile x600
Mjolnir Rage Heavy Assault Missile x600
Nova Rage Heavy Assault Missile x600
Scourge Javelin Heavy Assault Missile x600
Scourge Rage Heavy Assault Missile x864
Navy Cap Booster 800 x13
Nanite Repair Paste x600
Sisters Combat Scanner Probe x8
Noise-5 'Needlejack' Filament x5
Signal-5 'Needlejack' Filament x5
Border-5 'Pochven' Filament x2
Agency 'Overclocker' SB7 Dose III x4
Improved Exile Booster x2
Synth Crash Booster x4


[1] Federation Navy 100MN Afterburner
  Gravid 100MN Afterburner Mutaplasmid
  capacitorNeed 355.975, cpu 68.01025, power 562.75, speedFactor 153.41
```
2. Click Import a fit
3. Paste fit and click import
4. Observe that no indication of failure has occurred, open web console to review uncaught error.

**Comment by TrueBrain** [comment]
I knew I forgot something for the EFT imports :D  Good catch!

**Comment by TrueBrain** [comment]
Question: is that `[1]` in the fit something you added manually, or does any of the tools (like PyFa) generate it? I am curious if it has any meaning.

Edit: owh, it is PyFa's way of displaying an abyssal module?

**Comment by Grimnir09** [comment]
> Question: is that `[1]` in the fit something you added manually, or does any of the tools (like PyFa) generate it? I am curious if it has any meaning.
> 
> Edit: owh, it is PyFa's way of displaying an abyssal module?

Yeah I believe it's pyfa's way of parsing abyssals. I don't think in-game eft  includes abyssal information on the attribute changes.

**Comment by TrueBrain** [comment]
Tnx again for the report; I also fixed some other things with regards to EFT import/export. This is now available at https://eveship.fit/ !
